server:
  port: 8090

spring:
  application:
    name: CUSTOMER FEEDBACK
  datasource:
    url: jdbc:mysql://192.168.1.20:3306/customer_feedback
    username: root
    password: 123456789
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: none
    show-sql: true



