pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/NandkumarBankar/Customer-Feedback.git'
            }
        }

        stage('Build : Customer-Feedback ') {
            steps {
                dir('Customer-Feedback') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Test Project : Customer-Feedback') {
            steps {
                dir('Customer-Feedback') {
                    bat 'mvn test'
                }
            }
        }

        stage('Deploy Project : Customer-Feedback') {
                   steps {
//                        dir('Customer-Feedback') {
//                            // Kill the Java process running the specific JAR
//                            bat 'for /f "tokens=2" %%i in (\'tasklist /FI "IMAGENAME eq java.exe" /FI "WINDOWTITLE eq Customer-Feedback" /NH\') do taskkill /F /PID %%i'
//
//                            // Run the new JAR file in the background
//                            bat 'start /B java -jar target/Customer-Feedback.jar'
//                        }

                         dir('Customer-Feedback') {
                             bat 'java -jar target/Customer-Feedback.jar'
                         }
                   }
               }
           }

    post {
        always {
            echo "Cleaning up after execution"
        }
        success {
            echo "Build and deployment successful!"
        }
        failure {
            echo "Build or deployment failed!"
        }
    }
}
